version: "3.8"

services:
  frontend:
    build:
      context: ./reactConf
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/project
    command: sh -c 'npm install && npm run start'

  fake_server:
    image: maildev/maildev
    container_name: mail
    ports:
      - 1080:1080
      - 8025:8025

  backend:
    build:
      context: ./phpConf
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5656:80"
    volumes:
      - ./app:/var/www/html

  db:
    image: mariadb:10.8
    restart: always
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3500:3306"
    environment:
      MYSQL_DATABASE: react
      MYSQL_ROOT_PASSWORD: password

  newredis:
    container_name: newredis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./redis/data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "1333:8080"

volumes:
  db-data:
